# Use a base image with C++ compiler
FROM gcc:latest

# Set the working directory in the container
WORKDIR /app

# Copy the source code into the container
COPY emitter.cpp .

# Compile the C++ program
RUN g++ -o emitter emitter.cpp

# Run the C++ program
CMD ["./emitter"]
